# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSjuJO6DD9zoAZ06IuK-5UhJ5-OYRG3B
"""

import pandas as pd
teacher={
     'teachers':["Djalilov.M.L","Xontorayev.S.I","Arabboyev.A.A","Jo'rayeva.G.F","Xalilov.D.A"],
     'fan nomi':["Kompyuter tashkil etish","Ma'lumotlar tuzilmasi va algoritmal","Kiberxavfsizlik asoslari","Elektronika va sxemalari","Sun'iy intelekt"],
     'kafedrasi':["Kompyuter tizimlari","Axborot texnologiyalari","Axborot xavfsizligi","Telekamunikatsiya","Axbarot texnologiyalari"]
}
df=pd.DataFrame(teacher)
df=df.sort_values(by='teachers')
df = df.reset_index(drop=True)

print(df)

df.to_excel("614.xlsx")